F#src 5238 better pr testing
shadow-robot/aurora pull request #271
Opened 2020-09-11 13:39 UTC by ToivoS

2020-09-23 15:53 UTC, biofotis requested changes
It might not be a good time now but the run-ansible.sh is getting as big as the first oneliner that we tried to get away from.

2020-09-23 16:49 UTC, ToivoS commented on ansible/roles/products/common/docker-container/tasks/reinstall.yml
> +    shell: "docker cp {{ shadow_hand_launcher_folder }}/pull_pr_branches_and_catkin_make.sh {{ container_name }}:/home/user/pull_pr_branches_and_catkin_make.sh"
yes, it's fixed in the latest commit

2020-09-23 16:49 UTC, ToivoS commented
> It might not be a good time now but the run-ansible.sh is getting as big as the first oneliner that we tried to get away from.

2020-09-23 16:56 UTC, ToivoS commented
> It might not be a good time now but the run-ansible.sh is getting as big as the first oneliner that we tried to get away from.

run-ansible.sh is getting big because:
1) we do user-input validation (first oneliner didn't do that)
2) allows user-entered arguments which contain spaces inside quotes "val1 val2 val3" (first oneliner didn't do that)
3) checks if the user has got an SSH key which is registered with Github and asks user to create it while waiting for confirmation and then checking again (first oneliner didn't do that)
4) it's a good idea to do this input argument validation, handling spaces and SSH checks in run-ansible.sh because it avoids waiting a long time while ansible runs and goes to the correct section in the playbook (after installing docker, etc.) to check for those variables (and we would have to perform this check in multiple playbooks and multiple sections of the same playbook)

2020-09-24 12:19 UTC, biofotis approved these changes

2020-09-24 12:24 UTC, biofotis approved these changes

2020-09-24 12:24 UTC, merged