F#src5190 removesleeps
shadow-robot/aurora pull request #295
Opened 2020-11-02 09:17 UTC by giusebar

2020-11-02 11:02 UTC, mikramarc requested changes

2020-11-02 11:02 UTC, mikramarc commented on ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything-bimanual.j2
>  #jinja2: trim_blocks:False
same stuff in this file

2020-11-02 11:02 UTC, mikramarc commented on ansible/roles/products/hand-e/server/desktop-icons/templates/scripts/launch-everything-bimanual.j2
>  #jinja2: trim_blocks:False
and all files below

2020-11-03 12:29 UTC, ToivoS requested changes

2020-11-03 12:29 UTC, ToivoS commented on ansible/roles/products/hand-e/server/desktop-icons/tasks/main.yml
> +  import_tasks: default-icon.yml
Why this change: default-icon-no-terminator.yml -> default-icon.yml

2020-11-03 12:29 UTC, ToivoS requested changes
Why this change: default-icon-no-terminator.yml -> default-icon.yml

2020-11-04 09:03 UTC, mikramarc approved these changes

2020-11-04 09:14 UTC, ToivoS approved these changes

2020-11-04 09:15 UTC, merged