Src 5613 icons set proper payload
shadow-robot/aurora pull request #320
Opened 2020-12-16 16:37 UTC by georgiablanco

2020-12-17 10:47 UTC, biofotis requested changes
As it stands it wont work. You need to update the corresponding jinja file as well to accept this new argument

2021-01-04 17:46 UTC, ToivoS approved these changes

2021-01-05 12:29 UTC, mykolasjuraitis approved these changes

2021-01-05 14:00 UTC, biofotis approved these changes

2021-01-05 14:00 UTC, merged