Src 6862 pull from ecr
shadow-robot/aurora pull request #404
Opened 2022-02-08 16:42 UTC by BenStarmerSmith

## Proposed changes

Made changes to Aurora to allow it to pull Images from AWS ECR using the customer_key.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [x] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-02-11 14:33 UTC, biofotis requested changes

2022-02-11 14:33 UTC, biofotis commented on ansible/roles/installation/aws-cli/tasks/main.yml
> +- name: Install AWS CLI debian
please remove

2022-02-14 12:36 UTC, maxzieba approved these changes

2022-02-15 13:42 UTC, biofotis approved these changes

2022-02-15 13:42 UTC, merged