Sp 159 add further encryption
shadow-robot/aurora pull request #416
Opened 2022-03-18 10:32 UTC by BenStarmerSmith

## Proposed changes

This PR is used to further secure the docker_credentials that we pass from AWS to aurora. It also keeps the user's login details from aws configure before login in with the docker account. 

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-03-18 11:38 UTC, maxzieba requested changes

2022-03-18 11:38 UTC, maxzieba commented on ansible/roles/docker/ecr/files/decode.py
> +    parser.add_argument('--accesskey', '-a', type=str, required=True, help=help)
Can you add an undescore as word separator?

2022-03-21 10:44 UTC, ethanfowler approved these changes

2022-03-22 12:13 UTC, biofotis approved these changes

2022-03-22 12:15 UTC, merged