Fix 8dof icons
shadow-robot/aurora pull request #438
Opened 2022-04-26 08:52 UTC by BenStarmerSmith

## Proposed changes

Added 8dof icons for sim, fixed jog_arm icons too.

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [x] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [x] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-04-26 12:48 UTC, jeferrandiz98 approved these changes

2022-04-27 09:57 UTC, biofotis requested changes

2022-04-27 09:57 UTC, biofotis commented on ansible/roles/products/teleop/server/desktop-icons/templates/scripts/launch-teleop-right-8dof-sim.j2
> +terminator --geometry "{{ term_3 }}" -T 'Server Right Teleop Simulation' -e "{{ shadow_hand_launcher_folder}}/shadow_sim_left_8DOF.sh"
this should be right?

2022-04-27 11:52 UTC, biofotis approved these changes

2022-04-27 11:52 UTC, merged