Added new documentation for hand+glove.
shadow-robot/aurora pull request #464
Opened 2022-07-08 12:58 UTC by BenStarmerSmith

## Proposed changes

Added new documentation for hand+glove. Updated other outdated parts of the documentation too."

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2022-07-08 14:01 UTC, biofotis requested changes

2022-07-08 14:01 UTC, biofotis commented on README.md
> +Hand and Glove is another main product of the server_and_nuc playbook. This also takes in a new product type with product=glove_hand_e now, it also has extra parameters relating to the glove that you
Where is that options above? Can you rewrite this section as its not very clear?

2022-07-08 14:01 UTC, biofotis commented on README.md
> +new clean installation is performed. If the required image is private, then a valid Docker Hub account with pull credentials from Shadow Robot's Docker Hub is required. Then the specified docker imag
Here for private we use ecr

2022-07-12 08:53 UTC, biofotis approved these changes

2022-07-12 12:16 UTC, rnzenha-s approved these changes

2022-07-13 09:47 UTC, merged