F#swc 16 customer deployment checks
shadow-robot/aurora pull request #632
Opened 2024-12-09 12:17 UTC by carebare47

## Proposed changes

Adds script to check if deployment is likely to succeed

## Checklist

Before posting a PR ensure that from each of the below categories **AT LEAST ONE BOX HAS BEEN CHECKED**. If more than one category is applicable then more can be checked. Also ensure that the proposed changes have been filled out with relevant information for reviewers.

## Tests

- [ ] No tests required to be added. (For small changes that will be tested by CI/CD infrastructure).
- [ ] Added/Modified automated and PhantomHand CI tests (if a new class is added (Python or C++), the interface of that class must be unit tested).
- [ ] Manually tested in simulation (if simulation specific or no hardware required to test the functionality). 
- [ ] Manually tested on hardware (if hardware specific or related).

## Documentation

- [ ] No documentation required to be added.
- [ ] Added documentation (For any new feature, explain what it does and how to use it. Write the documentation in a relevant space, e.g. Github, Confluence, etc).
- [ ] Updated documentation (For changes to pre-existing features mentioned in the documentation).

2024-12-09 14:06 UTC, toliver requested changes

2024-12-09 14:14 UTC, toliver requested changes

2024-12-13 11:56 UTC, carebare47 commented on bin/sr_deployment_test.py
> +        self._test_classes_dict = {
that's a good point, thanks

2024-12-13 11:57 UTC, carebare47 commented on bin/sr_deployment_test.py
> +        self._system_info = GetSystemInfo()
oops, thanks

2024-12-13 11:59 UTC, carebare47 commented on bin/sr_deployment_test.py
> +        self._test_classes_dict = {
a379fbeb

2024-12-13 11:59 UTC, carebare47 commented on bin/sr_deployment_test.py
> +        self._system_info = GetSystemInfo()
a379fbeb

2024-12-13 11:59 UTC, carebare47 commented on bin/deployment-test.sh
> +REMOTE_PYTHON_FILE="https://raw.githubusercontent.com/shadow-robot/aurora/refs/heads/F%23SWC-16_customer_deployment_checks/bin/sr_deployment_test.py"
a379fbeb

2024-12-13 11:59 UTC, carebare47 commented on bin/deployment-test.sh
> +# python3 $LOCAL_PYTHON_FILE
a379fbeb

2025-01-06 10:35 UTC, niko-holmes requested changes

2025-01-07 13:50 UTC, niko-holmes requested changes
Looks good!

2025-01-07 13:50 UTC, niko-holmes commented on bin/deployment-test.sh
> +# Copyright 2024 Shadow Robot Company Ltd.
Dont forget 2025

2025-01-07 13:50 UTC, niko-holmes commented on bin/sr_deployment_test.py
> +# Copyright 2024 Shadow Robot Company Ltd.
```suggestion
# Copyright 2024, 2025 Shadow Robot Company Ltd.
```

2025-01-08 16:45 UTC, merged